CFLAGS=-Wall -g
.SILENT: fun

all:
	mkdir build
	cc ex1.c -o ./build/ex1 

clean:
	rm -fr build

run: 
	./ex1

fun: 
	# lsof -f 
	echo ""
	echo "Make can do all kinds of things."
	echo "This is why it is good to start with simple examples."
	
