CFLAGS=-Wall -g
.SILENT: fun

all:
	cc ex1.c -o ex1 

clean:
	rm -f ex1

run: 
	./ex1

fun: 
	# lsof -f 
	echo ""
	echo "Make can do all kinds of things."
	echo "This is why it is good to start with simple examples."
	
